// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoyJU-oxfLkVVACFd1JKUci6XqAZSjrwE',
    appId: '1:387271244589:web:e30462fecbc52a48ddf1a4',
    messagingSenderId: '387271244589',
    projectId: 'pdks-3a8fc',
    authDomain: 'pdks-3a8fc.firebaseapp.com',
    storageBucket: 'pdks-3a8fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOm5Oyb9PX6RPhtRaM5r-a-GxeRzqjBac',
    appId: '1:387271244589:android:082a980ad9d71421ddf1a4',
    messagingSenderId: '387271244589',
    projectId: 'pdks-3a8fc',
    storageBucket: 'pdks-3a8fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk0fSJzON0cWWoa-P-zTtHsu0yWHgbEjw',
    appId: '1:387271244589:ios:f12194557a1b2e5bddf1a4',
    messagingSenderId: '387271244589',
    projectId: 'pdks-3a8fc',
    storageBucket: 'pdks-3a8fc.appspot.com',
    iosBundleId: 'com.example.pdks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk0fSJzON0cWWoa-P-zTtHsu0yWHgbEjw',
    appId: '1:387271244589:ios:f12194557a1b2e5bddf1a4',
    messagingSenderId: '387271244589',
    projectId: 'pdks-3a8fc',
    storageBucket: 'pdks-3a8fc.appspot.com',
    iosBundleId: 'com.example.pdks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoyJU-oxfLkVVACFd1JKUci6XqAZSjrwE',
    appId: '1:387271244589:web:287249d4b885683cddf1a4',
    messagingSenderId: '387271244589',
    projectId: 'pdks-3a8fc',
    authDomain: 'pdks-3a8fc.firebaseapp.com',
    storageBucket: 'pdks-3a8fc.appspot.com',
  );
}
